-- products_spec_otr — OTR 제원(제품 SKU 1행 기준) 신설 (2026-08-04)
--
-- 원천 ① OTR_카탈로그_브랜드별_정리.xlsx '통합 목록' 19행
--        ('OTR Ascendo .pdf' 14행 + 'Leaflet Techking OTR.pdf' 5행, PT Ascendo Internasional 배포본)
--      ② 기존 specs_otr 마스터 174행(TECHKING 102 · ASCENDO 72) — 카탈로그에 없는 제품의 승계용
--
-- 매칭 원칙
--   1) PR 은 덮어쓰지 않는다. 제품·마스터 PR 과 카탈로그 PR 이 다르면 카탈로그 행을 쓰지 않고
--      마스터 값을 승계한 뒤 보고만 한다(하중·공기압이 PR 에 따라 달라짐). 해당 2건:
--        · OTR1-130024G2AS432  DB PR 16 ↔ 카탈로그 AS432 13.00-24 14PR
--        · OTR1-130025AE804    DB PR 28 ↔ 카탈로그 AE-804 13.00-25 32PR
--   2) 매칭 순서 = (브랜드·패턴·규격·PR) → (브랜드·패턴·규격) → (브랜드·규격·TRA코드·PR).
--      세 번째는 제품명이 패턴 대신 TRA 코드로 적힌 경우(OTR1-17525E3L320 'ASC 17.5-25 E-3/L-3 20PR')용이며
--      해당 조합의 카탈로그 행이 유일할 때만 인정한다 → AE-803 17.5-25 20PR 로 연결.
--   3) 중량 컬럼은 두지 않는다 — 스펙 탭이 products_priced.weight_kg 를 그대로 쓰도록.
--   4) specs_otr 마스터는 삭제하지 않는다 — 제품에 연결되지 않은 174행(TECHKING 사이즈 라인업 등)이 남아 있다.
--
-- 신규 컬럼(기존 specs_otr 에 없던 항목): construction(Radial/Bias) · star_rating(★) · tra_code ·
--   tread_depth_mm · tube_type(TT/TL) · rim_size · section_width_mm · overall_diameter_mm ·
--   pressure_10kmh_psi · pressure_50kmh_psi · load_index(LI&SS) · compound · features
-- 중복 컬럼(기존 유지): sku · brand · pattern · size · ply_rating · load_10kmh · load_50kmh ·
--   application · source_catalog
-- 미승계: tkph_rating(마스터 174행 전부 null), load_30kmh·load_40kmh(합계 3행, 제품 미연결),
--   weight_kg(마스터 전부 null)
-- load_index(LI & SS)·compound 는 컬럼만 만들어 둔다 — 카탈로그에서 값이 있는 행이 TECHKING 5행뿐인데
--   모두 취급 제품과 패턴이 달라 21행 전부 null. 값이 채워지기 전까지 스펙 탭 헤더에서는 제외한다.
--
-- 결과: OTR 제품 30건 중 21건에 제원 부여(신규 카탈로그 15 · 마스터 승계 6).
--   · 신규 제원 6건 — AD 907 14.00R25(M4·M7), AD 903 16.00R25(M4·M7), AD 905 29.5R25(H2·R1) 라디얼
--   · 값 정정 2건 — OTR1-140024G2AS432 @10km/h 공란→7300,
--                   OTR1-17525G2L220 @10km/h 공란→8250 · @50km/h 3650→5000
--   · 용도 표기는 카탈로그의 적용 장비명으로 통일(Loader Tyres → Grader 등)
--
-- 제원 없는 제품 9건: MAXAM 6종(MS905 13.00-24 · MS801 14.00-24 · MS905 14.00-24 · MS912 17.5-25 ·
--   MS904 19.5L-24 · MS913 20.5-25) — 카탈로그·마스터 어느 쪽에도 MAXAM 행이 없음.
--   TECHKING 3종(ETCRANE 14.00R24 · TK329 16.00R25 · SUPER TRAC 27.00R49) — 두 원천에 해당 패턴 없음.
--
-- 카탈로그 미사용 8행: ASCENDO AS432 13.00-24 14PR · AE-804 13.00-25 32PR(위 PR 불일치 2건),
--   AE-804 14.00-24 36PR(대응 제품 없음), TECHKING 5행(ETOT 14.00R24 · TKBL3 23.5-25 ·
--   MATE-S 23.5R25 · ETADT 26.5R25 · SUPER ADT 29.5R25 — 취급 제품과 패턴이 다름)

create table if not exists public.products_spec_otr (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  brand text,
  pattern text,
  size text,
  construction text,                 -- 구분: Radial / Bias
  ply_rating smallint,               -- PR(바이어스). 라디얼은 대신 star_rating 사용
  star_rating text,                  -- SR: ★★ / ★★★ (라디얼 하중등급)
  tra_code text,                     -- TRA 분류: E3 / E4 / L3 / G-2 등
  tread_depth_mm numeric,
  tube_type text,                    -- TT(Tube Type) / TL(Tubeless)
  rim_size text,                     -- 표준 림. '10.00/2.0'·'8.00TG' 표기가 있어 텍스트
  section_width_mm numeric,
  overall_diameter_mm numeric,
  load_10kmh integer,                -- 최대하중(kg) @10 km/h
  load_50kmh integer,                -- 최대하중(kg) @50 km/h
  pressure_10kmh_psi integer,        -- 최대공기압(psi) @10 km/h
  pressure_50kmh_psi integer,        -- 최대공기압(psi) @50 km/h
  load_index text,                   -- LI & SS (하중지수·속도기호)
  compound text,
  application text,                  -- 적용 장비
  features text,                     -- 주요 특징
  source_catalog text,
  created_at timestamptz not null default now()
);

alter table public.products_spec_otr enable row level security;
drop policy if exists otr_specs_read_auth on public.products_spec_otr;
create policy otr_specs_read_auth on public.products_spec_otr for select to authenticated using (true);
drop policy if exists otr_specs_write_admin on public.products_spec_otr;
create policy otr_specs_write_admin on public.products_spec_otr for all to authenticated
  using ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'))
  with check ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'));

insert into public.products_spec_otr (sku, brand, pattern, size, construction, ply_rating, star_rating, tra_code, tread_depth_mm, tube_type, rim_size, section_width_mm, overall_diameter_mm, load_10kmh, load_50kmh, pressure_10kmh_psi, pressure_50kmh_psi, load_index, compound, application, features, source_catalog) values
  ('1600R25ETRTV', 'TECHKING', 'ETRTV', '16.00R25', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'E4', null, 'TECHKING OTR 2026'),
  ('OTR1-130024G2AS432', 'ASCENDO', 'G-2 AS432', '13.00-24', null, 16, null, null, null, null, null, null, null, null, 3000, null, null, null, null, 'Loader Tyres', null, 'ASCENDO OTR 2026 (Rungold)'),
  ('OTR1-130025AE804', 'ASCENDO', 'E-3 AE804', '13.00-25', null, 28, null, null, null, null, null, null, null, 4600, null, null, null, null, null, 'Mine Tyres', null, 'ASCENDO OTR 2026 (Rungold)'),
  ('OTR1-140024E3L324', 'ASCENDO', 'E3/L3', '14.00-24', null, 24, null, null, null, null, null, null, null, 9500, 5150, null, null, null, null, 'Loader Tyres', null, 'ASCENDO OTR 2026 (Rungold)'),
  ('OTR1-140024G2AS432', 'ASCENDO', 'AS432', '14.00-24', 'Bias', 16, null, 'G-2', 24.5, 'TL', '8.00TG', 360, 1315, 7300, 3650, 80, 62, null, null, 'Grader', null, 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-140025AE804', 'ASCENDO', 'AE-804', '14.00-25', 'Bias', 36, null, 'E3', 27, 'TT', '10.00/1.5', 350, 1173, 11500, 6500, 174, 123, null, null, 'Heavy-Duty Dump Truck', null, 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-1400R25AD907M4', 'ASCENDO', 'AD 907', '14.00R25', 'Radial', null, '★★★', 'E3', 27, 'TL', '10.00/2.0', 363, 1365, 10000, 5800, 138, 102, null, null, 'Dump Truck', '우수한 트랙션, 내마모·내컷팅·내펑크, 높은 하중 지지력', 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-1400R25AD907M7', 'ASCENDO', 'AD 907', '14.00R25', 'Radial', null, '★★★', 'E3', 27, 'TL', '10.00/2.0', 363, 1365, 10000, 5800, 138, 102, null, null, 'Dump Truck', '우수한 트랙션, 내마모·내컷팅·내펑크, 높은 하중 지지력', 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-160025AE804', 'ASCENDO', 'AE-804', '16.00-25', 'Bias', 40, null, 'E3', 28, 'TT', '11.25/2.0', 390, 1461, 14500, 8000, 156, 125, null, null, 'Heavy-Duty Dump Truck', null, 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-1600R25AD903M4', 'ASCENDO', 'AD 903', '16.00R25', 'Radial', null, '★★★', 'E3', 30, 'TL', '11.25/2.0', 450, 1484, 12150, 7300, 120, 102, null, null, 'Dump Truck', '우수한 트랙션, 낮은 발열, 장거리 운송·고속 내마모 성능', 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-1600R25AD903M7', 'ASCENDO', 'AD 903', '16.00R25', 'Radial', null, '★★★', 'E3', 30, 'TL', '11.25/2.0', 450, 1484, 12150, 7300, 120, 102, null, null, 'Dump Truck', '우수한 트랙션, 낮은 발열, 장거리 운송·고속 내마모 성능', 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-17525AE803', 'ASCENDO', 'AE-803', '17.5-25', 'Bias', 20, null, 'E3/L3', 26, 'TT', '14.00/1.5', 445, 1292, 8250, 5000, 83, 58, null, null, 'Bulldozer / Loader', '광산·건설 노면용 트랜스버스 패턴, 고강도 카커스·내펑크·재생(Recapping) 우수', 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-17525E3L320', 'ASCENDO', 'AE-803', '17.5-25', 'Bias', 20, null, 'E3/L3', 26, 'TT', '14.00/1.5', 445, 1292, 8250, 5000, 83, 58, null, null, 'Bulldozer / Loader', '광산·건설 노면용 트랜스버스 패턴, 고강도 카커스·내펑크·재생(Recapping) 우수', 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-17525G2L220', 'ASCENDO', 'G-2/L-2', '17.5-25', 'Bias', 20, null, 'G-2/L-2', 24, 'TT', '14.00/1.5', 370, 1370, 8250, 5000, 83, 58, null, null, 'Grader / Loader', '험지용 로드 그레이더 타이어, 고무 보강 센터 러그로 수명 연장', 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-180025E3/L340', 'ASCENDO', 'E-3/L-3', '18.00-25', null, 40, null, null, null, null, null, null, null, 17000, 9750, null, null, null, null, 'Loader Tyres', null, 'ASCENDO OTR 2026 (Rungold)'),
  ('OTR1-20525AE803', 'ASCENDO', 'AE-803', '20.5-25', 'Bias', 20, null, 'E3/L3', 28, 'TT', '17.00/2.0', 510, 1388, 9500, 6000, 65, 47, null, null, 'Bulldozer / Loader', null, 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-23525AE803', 'ASCENDO', 'AE-803', '23.5-25', 'Bias', 20, null, 'E3/L3', 35.5, 'TT', '19.50/2.5', 595, 1522, 10900, 9500, 54, 44, null, null, 'Bulldozer / Loader', null, 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-26525AE803', 'ASCENDO', 'AE-803', '26.5-25', 'Bias', 32, null, 'E3/L3', 35, 'TT', '22.00/3.0', 590, 1620, 17000, 11200, 80, 62, null, null, 'Bulldozer / Loader', null, 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-29525E3/L332', 'ASCENDO', 'E3/L3', '29.5-25', null, 32, null, null, null, null, null, null, null, 18000, 12000, null, null, null, null, 'Loader Tyres', null, 'ASCENDO OTR 2026 (Rungold)'),
  ('OTR1-295R25AD905H2', 'ASCENDO', 'AD 905', '29.5R25', 'Radial', null, '★★', 'E3/L3', 41, 'TL', '25.00/3.5', 730, 1856, 22400, 14000, 94, 76, null, null, 'Heavy-Duty Dump Truck', '펜타곤 블록 조합 트랙션 최적화, 오픈 숄더 설계로 자가 세척(Self-Clean) 우수', 'OTR 통합 카탈로그 2026-08-04'),
  ('OTR1-295R25AD905R1', 'ASCENDO', 'AD 905', '29.5R25', 'Radial', null, '★★', 'E3/L3', 41, 'TL', '25.00/3.5', 730, 1856, 22400, 14000, 94, 76, null, null, 'Heavy-Duty Dump Truck', '펜타곤 블록 조합 트랙션 최적화, 오픈 숄더 설계로 자가 세척(Self-Clean) 우수', 'OTR 통합 카탈로그 2026-08-04')
on conflict (sku) do update set
  brand = excluded.brand,
  pattern = excluded.pattern,
  size = excluded.size,
  construction = excluded.construction,
  ply_rating = excluded.ply_rating,
  star_rating = excluded.star_rating,
  tra_code = excluded.tra_code,
  tread_depth_mm = excluded.tread_depth_mm,
  tube_type = excluded.tube_type,
  rim_size = excluded.rim_size,
  section_width_mm = excluded.section_width_mm,
  overall_diameter_mm = excluded.overall_diameter_mm,
  load_10kmh = excluded.load_10kmh,
  load_50kmh = excluded.load_50kmh,
  pressure_10kmh_psi = excluded.pressure_10kmh_psi,
  pressure_50kmh_psi = excluded.pressure_50kmh_psi,
  load_index = excluded.load_index,
  compound = excluded.compound,
  application = excluded.application,
  features = excluded.features,
  source_catalog = excluded.source_catalog;

-- 승계 행 정리: specs_otr 마스터의 TECHKING ETRTV 는 application 칸에 TRA 코드('E4')가 들어 있어 tra_code 로 옮긴다.
update public.products_spec_otr
set tra_code = 'E4', application = null
where sku = '1600R25ETRTV' and application = 'E4';
