-- IND(인도네시아) 솔리드·공기압 타이어 제원 테이블 신설 + 카탈로그 데이터 반영
--
-- 출처: '00-Working/_sql_ascendo/IND_솔리드_공기압_타이어_카탈로그_정리.xlsx' (2026-08-03)
--   · ASCENDO_솔리드   35행 (S2000 21 / NON MARKING 11 / S1000 3)
--   · ASCENDO_공기압    9행 (AB700, 튜브·플랩 블록은 제외)
--   · DIAMOND_솔리드   25행 (XN-018 2 / XN-028 7 / S200 16)
--
-- 구조는 products_spec_tbr 과 동일하게 **제품 SKU 1행** 규칙을 따른다
-- (스펙 탭이 products_priced 를 나열하고 sku 로 제원을 채우는 방식이라 규격/패턴 문자열
--  정규화 차이 -- '*' vs 'x', '(8.15-15)' 같은 괄호 표기 -- 에 매칭이 흔들리지 않게 하기 위함).
--
-- 카탈로그 원문 주석(※):
--   · ASCENDO 솔리드 하중은 Usage 'S'(지게차) 기준.
--   · NON MARKING = 백타이어(비마킹) 시리즈.
--   · DIAMOND S200 의 외경·단면폭은 원본이 cm 표기라 mm 로 환산(단, 7.50-16 의 OD 805 는 원본이 mm).
--   · DIAMOND 원본의 '21.8x-9' 는 21x8-9 의 오기.
--
-- 미매칭(카탈로그에 해당 규격·패턴 없음, 9건) — 제원 미기재로 남김:
--   ASC 250-15 AB700 / ASC 300-15 AB700 / ASC 8.25-14 AB700 / ASC 8.25-20 AB700 /
--   ASC 9.00-20 AB700 / ASC 28X9-15 AB702S / ASC 6.50-10 AB702S / ASC 8.25-15 HS800 14 /
--   ASC 23*10-12 S2000

create table if not exists public.products_spec_solid (
  id                   bigint generated by default as identity primary key,
  sku                  text not null unique,
  brand                text,
  pattern              text,
  size                 text,
  tire_type            text,
  rim_size             text,
  overall_diameter_mm  numeric,
  section_width_mm     numeric,
  weight_kg            numeric,
  load_kg              numeric,
  steer_load_kg        numeric,
  load_6kmh_kg         numeric,
  load_10kmh_kg        numeric,
  load_25kmh_kg        numeric,
  source_catalog       text,
  created_at           timestamptz not null default now()
);

create table if not exists public.products_spec_pneu (
  id                   bigint generated by default as identity primary key,
  sku                  text not null unique,
  brand                text,
  pattern              text,
  size                 text,
  ply_rating           smallint,
  tube_type            text,
  rim_size             text,
  overall_diameter_mm  numeric,
  section_width_mm     numeric,
  tread_depth_mm       numeric,
  weight_kg            numeric,
  max_load_kg          numeric,
  max_pressure_psi     numeric,
  source_catalog       text,
  created_at           timestamptz not null default now()
);

alter table public.products_spec_solid enable row level security;
alter table public.products_spec_pneu  enable row level security;

drop policy if exists solid_specs_read_auth   on public.products_spec_solid;
drop policy if exists solid_specs_write_admin on public.products_spec_solid;
drop policy if exists pneu_specs_read_auth    on public.products_spec_pneu;
drop policy if exists pneu_specs_write_admin  on public.products_spec_pneu;

create policy solid_specs_read_auth   on public.products_spec_solid for select to authenticated using (true);
create policy solid_specs_write_admin on public.products_spec_solid for all    to authenticated
  using ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'))
  with check ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'));
create policy pneu_specs_read_auth    on public.products_spec_pneu  for select to authenticated using (true);
create policy pneu_specs_write_admin  on public.products_spec_pneu  for all    to authenticated
  using ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'))
  with check ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'));

-- ── SOLID 69행 (ASCENDO 51 중 50 + DIAMOND 19) ──────────────────────────────
insert into public.products_spec_solid
  (sku, brand, pattern, size, tire_type, rim_size, overall_diameter_mm, section_width_mm,
   weight_kg, load_kg, steer_load_kg, load_6kmh_kg, load_10kmh_kg, load_25kmh_kg, source_catalog)
values
  ('10220100110200200', 'ASCENDO', 'Smooth', '10.00-20', 'Solid', '7.50', 1015, 218, 156.75, 6000, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220100110201000', 'ASCENDO', 'S2000', '10.00-20', 'Solid', '7.50', 1035, 253, 170.7, 6000, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220015450081000', 'ASCENDO', 'S2000', '15X4.5-8', 'Solid', '3.00D', 382, 109, 9.7, 1040, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220160110083000', 'ASCENDO', 'S2000', '16X6-8', 'Solid', '4.33R', 415, 148, 16.5, 1495, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220160110083002', 'ASCENDO', 'S2000', '16X6-8', 'Solid', '4.33R', 415, 148, 16.5, 1495, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220160110083003', 'ASCENDO', 'S2000', '16X6-8', 'Solid', '4.33R', 415, 148, 16.5, 1495, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220180110081000', 'ASCENDO', 'S2000', '18X7-8', 'Solid', '4.33R', 450, 153, 20.75, 2145, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220180110081001', 'ASCENDO', 'S2000', '18X7-8', 'Solid', '4.33R', 450, 153, 20.75, 2145, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220180110081003', 'ASCENDO', 'S2000', '18X7-8', 'Solid', '4.33R', 450, 153, 20.75, 2145, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220200500102000', 'ASCENDO', 'S2000', '200/50-10', 'Solid', '6.50F', 460, 195, 26, 2470, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220025110152000', 'ASCENDO', 'S2000', '2.50-15', 'Solid', '7.00', 715, 226, 69, 4745, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220025110151000', 'ASCENDO', 'S2000', '2.50-15', 'Solid', '7.00', 715, 226, 69, 4745, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220210110093000', 'ASCENDO', 'S2000', '21X8-9', 'Solid', '6.00E', 522, 185, 35, 2755, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220210110093001', 'ASCENDO', 'S2000', '21X8-9', 'Solid', '6.00E', 522, 185, 35, 2755, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220210110093003', 'ASCENDO', 'S2000', '21X8-9', 'Solid', '6.00E', 522, 185, 35, 2755, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220230110093000', 'ASCENDO', 'S2000', '23X9-10', 'Solid', '6.50F', 582, 203, 48.5, 3445, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220230110093001', 'ASCENDO', 'S2000', '23X9-10', 'Solid', '6.50F', 582, 203, 48.5, 3445, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220230110093003', 'ASCENDO', 'S2000', '23X9-10', 'Solid', '6.50F', 582, 203, 48.5, 3445, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220081110152000', 'ASCENDO', 'S2000', '28X9-15', 'Solid', '7.00', 688, 212, 59.2, 3445, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220081110152001', 'ASCENDO', 'S2000', '28X9-15', 'Solid', '7.00', 688, 212, 59.2, 3445, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220081110152003', 'ASCENDO', 'S2000', '28X9-15 (8.15-15)', 'Solid', '7.00', 688, 212, 59.2, 3445, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220030110151000', 'ASCENDO', 'S2000', '3.00-15', 'Solid', '8.00', 802, 258, 109, 5850, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220300110153000', 'ASCENDO', 'S2000', '3.00-15', 'Solid', '8.00', 802, 258, 109, 5850, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220300110153001', 'ASCENDO', 'S2000', '3.00-15', 'Solid', '8.00', 802, 258, 109, 5850, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220040110080200', 'ASCENDO', 'S200 RIB', '4.00-8', 'Solid', '3.00D', 404, 113, 11.3, 950, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220050110081000', 'ASCENDO', 'S2000', '5.00-8', 'Solid', '3.00D', 452, 120, 16.35, 1415, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220050110081001', 'ASCENDO', 'S2000', '5.00-8', 'Solid', '3.00D', 452, 120, 16.35, 1415, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220050110081003', 'ASCENDO', 'S2000', '5.00-8', 'Solid', '3.00D', 452, 120, 16.35, 1415, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220060110152000', 'ASCENDO', 'S2000', '6.00-15', 'Solid', '4.50E', 690, 153, 43, 2455, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220060110091000', 'ASCENDO', 'S1000', '6.00-9', 'Solid', '4.00', 525, 145, 27.6, 1885, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220060110093000', 'ASCENDO', 'S1000', '6.00-9', 'Solid', '4.00', 525, 145, 27.6, 1885, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220060110091003', 'ASCENDO', 'S1000', '6.00-9', 'Solid', '4.00', 525, 145, 27.6, 1885, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220060110092000', 'ASCENDO', 'S2000', '6.00-9', 'Solid', '4.00', 525, 145, 27.6, 1885, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220065110101000', 'ASCENDO', 'S1000', '6.50-10', 'Solid', '5.00', 572, 168, 38, 2340, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220065110101001', 'ASCENDO', 'S1000', '6.50-10', 'Solid', '5.00', 572, 168, 38, 2340, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220065110101003', 'ASCENDO', 'S1000', '6.50-10', 'Solid', '5.00', 572, 168, 38, 2340, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220065110102000', 'ASCENDO', 'S2000', '6.50-10', 'Solid', '5.00', 572, 162, 36.5, 2340, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220070110121000', 'ASCENDO', 'S1000', '7.00-12', 'Solid', '5.00', 655, 173, 48.9, 2920, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220070110123000', 'ASCENDO', 'S1000', '7.00-12', 'Solid', '5.00', 655, 173, 48.9, 2920, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220070110121003', 'ASCENDO', 'S1000', '7.00-12', 'Solid', '5.00', 655, 173, 48.9, 2920, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220070110151000', 'ASCENDO', 'S2000', '7.00-15', 'Solid', '5.50', 733, 171, 57.7, 3545, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220700110153000', 'ASCENDO', 'S2000', '7.00-15', 'Solid', '5.50', 733, 171, 57.7, 3545, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220700110153001', 'ASCENDO', 'S2000', '7.00-15', 'Solid', '5.50', 733, 171, 57.7, 3545, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220075110163000', 'ASCENDO', 'S2000', '7.50-16', 'Solid', '6.00', 780, 199, 76.6, 3950, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220075110163001', 'ASCENDO', 'S2000', '7.50-16', 'Solid', '6.00', 780, 199, 76.6, 3950, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220075110163003', 'ASCENDO', 'S2000', '7.50-16', 'Solid', '6.00', 780, 199, 76.6, 3950, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220085110153000', 'ASCENDO', 'S2000', '8.25-15', 'Solid', '6.50F', 810, 208, 91, 4750, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220085110153001', 'ASCENDO', 'S2000', '8.25-15', 'Solid', '6.50F', 810, 208, 91, 4750, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220085110153003', 'ASCENDO', 'S2000', '8.25-15', 'Solid', '6.50F', 810, 208, 91, 4750, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('10220090110201000', 'ASCENDO', 'S2000', '9.00-20', 'Solid', '7.00', 997, 233, 151, 5400, null, null, null, null, 'ASCENDO SOLID 2026'),
  ('1022018011008XN00', 'DIAMOND', 'XN-028 (S400)', '18X7-8', 'Solid', '4.33', 452, 165, 21.8, 2145, 1650, 2145, 1945, 1650, 'DIAMOND SOLID 2026'),
  ('1022006511010XN03', 'DIAMOND', 'XN-028 (S400)', '18X7-8', 'Solid', '4.33', 452, 165, 21.8, 2145, 1650, 2145, 1945, 1650, 'DIAMOND SOLID 2026'),
  ('1022021011009XN00', 'DIAMOND', 'XN-028 (S400)', '21X8-9', 'Solid', '6.00', 526, 190, 34.4, 2755, 2120, 2755, 2500, 2120, 'DIAMOND SOLID 2026'),
  ('1022006011009XN03', 'DIAMOND', 'XN-028 (S400)', '21X8-9', 'Solid', '6.00', 526, 190, 34.4, 2755, 2120, 2755, 2500, 2120, 'DIAMOND SOLID 2026'),
  ('1022023011009XN00', 'DIAMOND', 'XN-018 (S300)', '23X9-10', 'Solid', '6.50', 592, 202, 47.8, 3445, 2650, 3445, 3125, 2650, 'DIAMOND SOLID 2026'),
  ('1022023011009XN03', 'DIAMOND', 'XN-018 (S300)', '23X9-10', 'Solid', '6.50', 592, 202, 47.8, 3445, 2650, 3445, 3125, 2650, 'DIAMOND SOLID 2026'),
  ('1022023011009XN02', 'DIAMOND', 'XN-018 (S300)', '23X9-10', 'Solid', '6.50', 592, 202, 47.8, 3445, 2650, 3445, 3125, 2650, 'DIAMOND SOLID 2026'),
  ('1022008111015XN00', 'DIAMOND', 'XN-028 (S400)', '28X9-15', 'Solid', '7.00', 699, 218, 59.3, 3900, 3000, 3900, 3540, 3000, 'DIAMOND SOLID 2026'),
  ('1022008111015XN03', 'DIAMOND', 'XN-028 (S400)', '28X9-15', 'Solid', '7.00', 699, 218, 59.3, 3900, 3000, 3900, 3540, 3000, 'DIAMOND SOLID 2026'),
  ('1022005011008XN00', 'DIAMOND', 'XN-028 (S400)', '5.00-8', 'Solid', '3.00', 455, 120, 15.4, 1415, 1090, 1415, 1285, 1090, 'DIAMOND SOLID 2026'),
  ('1022005011008XN03', 'DIAMOND', 'XN-028 (S400)', '5.00-8', 'Solid', '3.00', 455, 120, 15.4, 1415, 1090, 1415, 1285, 1090, 'DIAMOND SOLID 2026'),
  ('1022006011009XN00', 'DIAMOND', 'XN-028 (S400)', '6.00-9', 'Solid', '4.00', 530, 143, 25.4, 1885, 1450, 1885, 1710, 1450, 'DIAMOND SOLID 2026'),
  ('1022018011008XN03', 'DIAMOND', 'XN-028 (S400)', '6.00-9', 'Solid', '4.00', 530, 143, 25.4, 1885, 1450, 1885, 1710, 1450, 'DIAMOND SOLID 2026'),
  ('1022006511010XN00', 'DIAMOND', 'XN-028 (S400)', '6.50-10', 'Solid', '5.00', 576, 162, 35.4, 2340, 1800, 2340, 2125, 1800, 'DIAMOND SOLID 2026'),
  ('1022021011009XN03', 'DIAMOND', 'XN-028 (S400)', '6.50-10', 'Solid', '5.00', 576, 162, 35.4, 2340, 1800, 2340, 2125, 1800, 'DIAMOND SOLID 2026'),
  ('1022007011012XN00', 'DIAMOND', 'XN-028 (S400)', '7.00-12', 'Solid', '5.00', 660, 177, 47.9, 2920, 2240, 2920, 2645, 2240, 'DIAMOND SOLID 2026'),
  ('1022007011012XN03', 'DIAMOND', 'XN-028 (S400)', '7.00-12', 'Solid', '5.00', 660, 177, 47.9, 2920, 2240, 2920, 2645, 2240, 'DIAMOND SOLID 2026'),
  ('1022008511015XN00', 'DIAMOND', 'XN-018 (S300)', '8.25-15', 'Solid', '6.50', 819, 212, 92, 4615, 3550, 4615, 4190, 3550, 'DIAMOND SOLID 2026'),
  ('1022008511015XN03', 'DIAMOND', 'XN-018 (S300)', '8.25-15', 'Solid', '6.50', 819, 212, 92, 4615, 3550, 4615, 4190, 3550, 'DIAMOND SOLID 2026')
on conflict (sku) do update set
  brand = excluded.brand, pattern = excluded.pattern, size = excluded.size,
  tire_type = excluded.tire_type, rim_size = excluded.rim_size,
  overall_diameter_mm = excluded.overall_diameter_mm, section_width_mm = excluded.section_width_mm,
  weight_kg = excluded.weight_kg, load_kg = excluded.load_kg, steer_load_kg = excluded.steer_load_kg,
  load_6kmh_kg = excluded.load_6kmh_kg, load_10kmh_kg = excluded.load_10kmh_kg,
  load_25kmh_kg = excluded.load_25kmh_kg, source_catalog = excluded.source_catalog;

-- ── PNEU 13행 (ASCENDO AB700) ───────────────────────────────────────────────
insert into public.products_spec_pneu
  (sku, brand, pattern, size, ply_rating, tube_type, rim_size, overall_diameter_mm,
   section_width_mm, tread_depth_mm, weight_kg, max_load_kg, max_pressure_psi, source_catalog)
values
  ('PNE-1878-AB700', 'ASCENDO', 'AB700', '18X7-8', 14, 'TT', '4.33R', 465, 173, 16, 8.05, 1440, 130, 'ASCENDO PNEUMATIC AB700 2026'),
  ('I1-28915700', 'ASCENDO', 'AB700', '28X9-15', 16, 'TT', '7.00', 690, 220, 19, 24.5, 3115, 145, 'ASCENDO PNEUMATIC AB700 2026'),
  ('PNE-28915-AB700', 'ASCENDO', 'AB700', '28X9-15', 16, 'TT', '7.00', 690, 220, 19, 24.5, 3115, 145, 'ASCENDO PNEUMATIC AB700 2026'),
  ('PNE-5008-AB700', 'ASCENDO', 'AB700', '5.00-8', 10, 'TT', '3.50D', 470, 137, 12, 6.39, 1150, 145, 'ASCENDO PNEUMATIC AB700 2026'),
  ('PNE-6009-AB700', 'ASCENDO', 'AB700', '6.00-9', 12, 'TT', '4.00E', 533, 160, 14, 9.5, 1675, 150, 'ASCENDO PNEUMATIC AB700 2026'),
  ('I1-6009700', 'ASCENDO', 'AB700', '6.00-9', 12, 'TT', '4.00E', 533, 160, 14, 9.5, 1675, 150, 'ASCENDO PNEUMATIC AB700 2026'),
  ('PNE-65010-AB700', 'ASCENDO', 'AB700', '6.50-10', 12, 'TT', '5.00F', 586, 190, 15, 12, 1895, 125, 'ASCENDO PNEUMATIC AB700 2026'),
  ('I1-65010700', 'ASCENDO', 'AB700', '6.50-10', 12, 'TT', '5.00F', 586, 190, 15, 12, 1895, 125, 'ASCENDO PNEUMATIC AB700 2026'),
  ('I1-70012700', 'ASCENDO', 'AB700', '7.00-12', 12, 'TT', '5.00S', 665, 190, 16.5, 18.5, 2375, 125, 'ASCENDO PNEUMATIC AB700 2026'),
  ('PNE-70012-AB700', 'ASCENDO', 'AB700', '7.00-12', 12, 'TT', '5.00S', 665, 190, 16.5, 18.5, 2375, 125, 'ASCENDO PNEUMATIC AB700 2026'),
  ('PNE-7009-AB700', 'ASCENDO', 'AB700', '7.00-9', 10, 'TT', '5.00S', 590, 190, 14, 12.05, 1995, 125, 'ASCENDO PNEUMATIC AB700 2026'),
  ('PNE-82512-AB700', 'ASCENDO', 'AB700', '8.25-12', 12, 'TT', '6.50', 765, 235, 18, 22.18, 3060, 105, 'ASCENDO PNEUMATIC AB700 2026'),
  ('PNE-82515-AB700', 'ASCENDO', 'AB700', '8.25-15', 14, 'TT', '6.50', 820, 235, 19.5, 31, 3775, 120, 'ASCENDO PNEUMATIC AB700 2026')
on conflict (sku) do update set
  brand = excluded.brand, pattern = excluded.pattern, size = excluded.size,
  ply_rating = excluded.ply_rating, tube_type = excluded.tube_type, rim_size = excluded.rim_size,
  overall_diameter_mm = excluded.overall_diameter_mm, section_width_mm = excluded.section_width_mm,
  tread_depth_mm = excluded.tread_depth_mm, weight_kg = excluded.weight_kg,
  max_load_kg = excluded.max_load_kg, max_pressure_psi = excluded.max_pressure_psi,
  source_catalog = excluded.source_catalog;
