-- products_spec_flap / products_spec_gis — FLAP·재생타이어(VUL) 제원 신설 (2026-08-04)
--
-- 원천 ① ASCENDO_FLAP_카탈로그_공장규격_대조.xlsx
--        · 시트1 'FLAP 카탈로그' 26행 — 자사 Flap Ascendo.pdf 기준(구분·SIZE·TYPE·QTY/SACK)에
--          공장 카탈로그(Shanxi Huajun, CATALOG FLAP JUL 2026 p.04) 규격·폭·중량을 대조한 표
--        · 시트2 '공장 카탈로그 원본' 35행 — 공장 전 규격 리스트(SIZE·Width·Weight)
--      ② GIS_재생타이어_트레드_사양표.xlsx (Leaflet Gis .pdf)
--        · 시트1 'GIS 트레드 사양' 10행(패턴×규격), 시트2 '패턴별 특성' 4행(패턴 단위)
--
-- FLAP 매칭 원칙
--   1) 키 = (타입 Standard|Metal Plate, 규격). 타입이 다른 행으로 대체하지 않는다(보강 사양·중량이 다름).
--   2) 자사 카탈로그(시트1) 우선. 시트1 미등재 규격만 공장 원본(시트2)으로 폭·중량을 보완한다.
--   3) 규격 표기는 3~4자리 숫자 덩어리에 소수점을 넣어 대조(750→7.50, 1300→13.00, 825R/900R20→8.25/9.00R20).
--   4) 공장 기준 폭·중량은 width_mm/ref_weight_kg 로 따로 두고, 화면의 WT (kg) 는 자사 실중량
--      (products_priced.weight_kg)을 그대로 쓴다 — 두 값을 섞지 않는다.
--   결과: FLAP 제품 52건 전부 제원 부여(시트1 매칭 44 · 시트2 보완 8).
--   공장 카탈로그 대조(match_status): Exact 20 · Notation diff. 19 · Not listed 13.
--
-- FLAP 확인 필요
--   · 공장 미등재 4종(자사 SKU 13건) — 7.00/7.50R16, 8.25/9.00R20, 10.00/11.00R20, 13.00/14.00-24.
--     특히 10.00/11.00R20 은 SKU 4건. 생산 가능 여부·대체 규격 확인 요청 대상.
--   · 제품 설명의 (H)/(S) 등급은 두 카탈로그 어디에도 구분이 없어 같은 규격이면 같은 제원을 넣었다.
--     실중량은 (H)가 더 무겁다(예: 10.00/11.00R20 H 2.35 kg / S 2.05 kg) — 등급 정의 확인 필요.
--   · TRUCKORR 7건은 ASCENDO 동일 규격 행을 그대로 받았다(products_priced 실중량이 ASCENDO (H)와 동일).
--   · 9.00/10.00R20 은 공장 원본에 일반(215 mm·2.4 kg)과 Radial(232 mm·3.2 kg) 두 행이 있어 일반 행을 적용,
--     remarks 에 병기했다. 11.00/12.00R20 도 공장 원본에 2.8 kg / 3.0 kg 두 행이 중복 등재되어 있다.
--   · 자사 카탈로그 표기 정비 필요 — Metal Plate 라인의 750/825R16 · 825R/900R20 이 Standard 라인
--     (7.50/8.25R16 · 8.25/9.00R20)과 표기 불일치, OTR Standard 1600-25 행의 TYPE 이 'Standart' 오기.
--
-- GIS(VUL) 매칭 원칙
--   1) (패턴, 규격) 완전일치만 인정. 리플릿에 없는 조합을 유사 규격 행으로 대체하지 않는다.
--   2) 시트2의 형상·장착위치·영업포인트는 패턴 단위 정보라 매칭된 행에 함께 붙인다.
--   결과: Jadi 13 + Jasa 14 = 27건 중 18건 제원 부여.
--
-- GIS 확인 필요
--   · 미매칭 9건 — AJ-101 × 레디얼 규격 8건(7.50R16 · 10.00R20 · 11.00R20 · 11R22.5 각 Jadi/Jasa)과
--     VULGIS 295/80R22.5 AJ104. 리플릿의 AJ-101 은 바이어스 4규격뿐이고 레디얼 전용은 AJ-104 다.
--     제품명 패턴 오기인지, AJ-101 트레드를 레디얼 케이싱에 적용하는 것인지 확인 필요.
--   · 리플릿 AJ-104 7.50R16 행은 대응 제품이 없어 미사용.
--   · AJ-105 10.00-20 은 기재 3.35 kg/m 과 계산값(10.25 ÷ 3.200 m = 3.20)이 약 4.6% 차이 — 공장 확인 필요.
--     그 외 규격은 반올림 오차(±1%) 범위라 리플릿 기재값을 그대로 넣었다.
--   · 12.00R20 · 12R22.5 등 인니 TBR 주력 규격은 리플릿 미수록.
--
-- 중복 컬럼 확인: FLAP·VUL 은 기존 스펙 테이블이 없어(스펙 탭에서 제원 컬럼 자체가 없던 카테고리)
--   중복 컬럼이 없다. 공통 규약대로 sku·brand·size·source_catalog 를 두고, 중량은 products_priced 를 쓴다.
-- 용어·단위는 CLAUDE.md 「제원(스펙) 표기 규칙」에 따라 영문·약어로 통일했다.

create table if not exists public.products_spec_flap (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  brand text,
  size text,
  flap_type text,                    -- Standard / Metal Plate
  tyre_class text,                   -- TBR / OTR (자사 카탈로그 '구분')
  qty_sack smallint,                 -- QTY/SACK (EA)
  factory_size text,                 -- 공장 카탈로그 규격 표기
  width_mm numeric,                  -- 공장 카탈로그 기준 폭
  ref_weight_kg numeric,             -- 공장 카탈로그 기준 중량(자사 실중량 products_priced.weight_kg 와 별개)
  match_status text,                 -- Exact / Notation diff. / Not listed
  remarks text,
  source_catalog text,
  created_at timestamptz not null default now()
);
alter table public.products_spec_flap enable row level security;
drop policy if exists flap_specs_read_auth on public.products_spec_flap;
create policy flap_specs_read_auth on public.products_spec_flap for select to authenticated using (true);
drop policy if exists flap_specs_write_admin on public.products_spec_flap;
create policy flap_specs_write_admin on public.products_spec_flap for all to authenticated
  using ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'))
  with check ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'));

create table if not exists public.products_spec_gis (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  brand text,
  pattern text,                      -- AJ-101 / AJ-104 / AJ-105 / AJ-301
  size text,
  construction text,                 -- Bias / Radial
  base_width_mm numeric,             -- BW: 트레드 바닥 폭
  skid_depth_mm numeric,             -- SD: 트레드 홈 깊이
  roll_length_mm numeric,
  weight_kg_roll numeric,
  weight_kg_m numeric,
  tread_shape text,                  -- Lug / Block / Rib-Block — 리플릿 이미지 기준 육안 분류
  position text,                     -- Drive / All Position
  application text,
  source_catalog text,
  created_at timestamptz not null default now()
);
alter table public.products_spec_gis enable row level security;
drop policy if exists gis_specs_read_auth on public.products_spec_gis;
create policy gis_specs_read_auth on public.products_spec_gis for select to authenticated using (true);
drop policy if exists gis_specs_write_admin on public.products_spec_gis;
create policy gis_specs_write_admin on public.products_spec_gis for all to authenticated
  using ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'))
  with check ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'));

insert into public.products_spec_flap (sku, brand, size, flap_type, tyre_class, qty_sack, factory_size, width_mm, ref_weight_kg, match_status, remarks, source_catalog) values
  ('11100000001', 'ASCENDO', '7.00/7.50R15', 'Standard', 'TBR', 20, '7.00/7.50-15', 175.0, 1.1, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000002', 'ASCENDO', '7.00/7.50R16', 'Standard', 'TBR', 20, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000003', 'ASCENDO', '7.50/8.25R16', 'Standard', 'TBR', 20, '7.50/8.25R16', 180.0, 1.4, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000004', 'ASCENDO', '8.25/9.00R20', 'Standard', 'TBR', 10, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000005', 'ASCENDO', '10.00/11.00R20', 'Standard', 'TBR', 10, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000006', 'ASCENDO', '11.00/12.00R20', 'Standard', 'TBR', 10, '11.00/12.00R20', 235.0, 2.8, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000007', 'ASCENDO', '12.00R24', 'Standard', 'TBR', 10, '12.00R24', 240.0, 3.3, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000010', 'ASCENDO', '7.50/8.25R16', 'Metal Plate', 'TBR', 20, '7.50/8.25R16', 180.0, 1.4, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000012', 'ASCENDO', '10.00/11.00R20', 'Metal Plate', 'TBR', 10, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000013', 'ASCENDO', '11.00/12.00R20', 'Metal Plate', 'TBR', 10, '11.00/12.00R20 Reinforce', 235.0, 3.8, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000034', 'ASCENDO', '18.00-25', 'Standard', 'OTR', 5, '16.00/18.00R25', 275.0, 5.3, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000021', 'ASCENDO', '20.5-25', 'Standard', 'OTR', 4, '20.5R25', 425.0, 6.8, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000022', 'ASCENDO', '23.5-25', 'Standard', 'OTR', 2, '23.5-25', 527.0, 9.6, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000014', 'ASCENDO', '12.00R24', 'Metal Plate', 'TBR', 10, '12.00R24', 240.0, 3.3, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000031', 'ASCENDO', '16.00-25', 'Metal Plate', 'OTR', 5, '16.00/18.00R25', 275.0, 5.3, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000025', 'ASCENDO', '17.5-25', 'Metal Plate', 'OTR', 5, '17.5R25', 320.0, 5.7, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000032', 'ASCENDO', '18.00-25', 'Metal Plate', 'OTR', 5, '16.00/18.00R25', 275.0, 5.3, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('81100000003', 'TRUCKORR', '7.50/8.25R16', 'Standard', 'TBR', 20, '7.50/8.25R16', 180.0, 1.4, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('81100000005', 'TRUCKORR', '10.00/11.00R20', 'Standard', 'TBR', 10, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('81100000008', 'TRUCKORR', '12.00R24', 'Metal Plate', 'TBR', 10, '12.00R24', 240.0, 3.3, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000016', 'ASCENDO', '9.00/10.00R20', 'Metal Plate', null, null, '9.00/10.00R20', 215.0, 2.4, 'Exact', 'Factory catalog lists 2 rows for this size: 9.00/10.00R20 2.4 kg / 9.00/10.00R20 Radial 3.2 kg', 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000028', 'ASCENDO', '7.50/8.25R20', 'Metal Plate', null, null, '7.50/8.25R20', 180.0, 1.7, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('81100000007', 'TRUCKORR', '12.00R24', 'Standard', 'TBR', 10, '12.00R24', 240.0, 3.3, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('81100000002', 'TRUCKORR', '7.00/7.50R16', 'Standard', 'TBR', 20, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('81100000001', 'TRUCKORR', '7.00/7.50R15', 'Standard', 'TBR', 20, '7.00/7.50-15', 175.0, 1.1, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000015', 'ASCENDO', '7.50/8.25R20', 'Standard', null, null, '7.50/8.25R20', 180.0, 1.7, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('211000000010', 'ASCENDO', '7.50/8.25R16', 'Metal Plate', 'TBR', 20, '7.50/8.25R16', 180.0, 1.4, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('21100000007', 'ASCENDO', '12.00R24', 'Standard', 'TBR', 10, '12.00R24', 240.0, 3.3, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('211000000014', 'ASCENDO', '11.00/12.00R20', 'Metal Plate', 'TBR', 10, '11.00/12.00R20 Reinforce', 235.0, 3.8, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('51100000017', 'ASCENDO', '13.00/14.00-24', 'Metal Plate', 'OTR', 8, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('51100000018', 'ASCENDO', '13.00/14.00-25', 'Metal Plate', 'OTR', 5, '13.00/14.00R25', 265.0, 4.8, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('211000000013', 'ASCENDO', '10.00/11.00R20', 'Metal Plate', 'TBR', 10, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000011', 'ASCENDO', '8.25/9.00R20', 'Metal Plate', 'TBR', 10, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000026', 'ASCENDO', '20.5-25', 'Metal Plate', 'OTR', 4, '20.5R25', 425.0, 6.8, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000027', 'ASCENDO', '23.5-25', 'Metal Plate', 'OTR', 2, '23.5-25', 527.0, 9.6, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('81100000006', 'TRUCKORR', '11.00/12.00R20', 'Standard', 'TBR', 10, '11.00/12.00R20', 235.0, 2.8, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000008', 'ASCENDO', '6.50/7.00R16', 'Standard', null, null, '6.50/7.00R16', 170.0, 1.1, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('51100000027', 'ASCENDO', '7.00-12', 'Standard', null, null, '7.00-12', 132.0, 0.8, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('51100000025', 'ASCENDO', '6.00-9', 'Standard', null, null, '6.00-9', 120.0, 0.4, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('51100000026', 'ASCENDO', '6.50-10', 'Standard', null, null, '6.50-10', 130.0, 0.5, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000023', 'ASCENDO', '13.00/14.00-24', 'Metal Plate', 'OTR', 8, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('51100000029', 'ASCENDO', '28*9-15/8.25-15', 'Standard', null, null, '28*9/8.25-15', 180.0, 1.5, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000024', 'ASCENDO', '13.00/14.00-25', 'Metal Plate', 'OTR', 5, '13.00/14.00R25', 265.0, 4.8, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000018', 'ASCENDO', '13.00/14.00-24', 'Standard', 'OTR', 8, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000019', 'ASCENDO', '13.00/14.00-25', 'Standard', 'OTR', 5, '13.00/14.00R25', 265.0, 4.8, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000030', 'ASCENDO', '16.00-25', 'Standard', 'OTR', 5, '16.00/18.00R25', 275.0, 5.3, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('11100000020', 'ASCENDO', '17.5-25', 'Standard', 'OTR', 5, '17.5R25', 320.0, 5.7, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('21100000001', 'ASCENDO', '7.00/7.50R15', 'Standard', 'TBR', 20, '7.00/7.50-15', 175.0, 1.1, 'Notation diff.', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('21100000002', 'ASCENDO', '7.00/7.50R16', 'Standard', 'TBR', 20, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('21100000003', 'ASCENDO', '7.50/8.25R16', 'Standard', 'TBR', 20, '7.50/8.25R16', 180.0, 1.4, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('21100000005', 'ASCENDO', '10.00/11.00R20', 'Standard', 'TBR', 10, null, null, null, 'Not listed', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)'),
  ('21100000006', 'ASCENDO', '11.00/12.00R20', 'Standard', 'TBR', 10, '11.00/12.00R20', 235.0, 2.8, 'Exact', null, 'Flap Ascendo + Shanxi Huajun CATALOG FLAP (JUL 2026)')
on conflict (sku) do update set
  brand = excluded.brand,
  size = excluded.size,
  flap_type = excluded.flap_type,
  tyre_class = excluded.tyre_class,
  qty_sack = excluded.qty_sack,
  factory_size = excluded.factory_size,
  width_mm = excluded.width_mm,
  ref_weight_kg = excluded.ref_weight_kg,
  match_status = excluded.match_status,
  remarks = excluded.remarks,
  source_catalog = excluded.source_catalog;

insert into public.products_spec_gis (sku, brand, pattern, size, construction, base_width_mm, skid_depth_mm, roll_length_mm, weight_kg_roll, weight_kg_m, tread_shape, position, application, source_catalog) values
  ('G175016AJ101', 'GIS', 'AJ-101', '7.50-16', 'Bias', 145.0, 13.0, 2420.0, 4.8, 1.97, 'Lug', 'Drive', 'Unpaved roads and construction sites; standard spec for traction-oriented routes', 'GIS ECO RETREAD Leaflet 2026'),
  ('G190020AJ101', 'GIS', 'AJ-101', '9.00-20', 'Bias', 193.0, 14.0, 3167.0, 10.1, 3.18, 'Lug', 'Drive', 'Unpaved roads and construction sites; standard spec for traction-oriented routes', 'GIS ECO RETREAD Leaflet 2026'),
  ('G1100020AJ101', 'GIS', 'AJ-101', '10.00-20', 'Bias', 204.0, 14.0, 3167.0, 10.1, 3.18, 'Lug', 'Drive', 'Unpaved roads and construction sites; standard spec for traction-oriented routes', 'GIS ECO RETREAD Leaflet 2026'),
  ('G1100020AJ105', 'GIS', 'AJ-105', '10.00-20', 'Bias', 194.0, 15.0, 3200.0, 10.25, 3.35, 'Rib-Block', 'All Position', 'Mixed on/off-road routes; general-purpose replacement for bias vehicles', 'GIS ECO RETREAD Leaflet 2026'),
  ('G1100020AJ301', 'GIS', 'AJ-301', '10.00-20', 'Bias', 205.0, 16.5, 3195.0, 10.1, 3.18, 'Block', 'Drive', 'Deepest skid depth in the range; mining and heavy-load routes, priced on wear life', 'GIS ECO RETREAD Leaflet 2026'),
  ('G1110020AJ101', 'GIS', 'AJ-101', '11.00-20', 'Bias', 204.0, 14.0, 3245.0, 11.15, 3.44, 'Lug', 'Drive', 'Unpaved roads and construction sites; standard spec for traction-oriented routes', 'GIS ECO RETREAD Leaflet 2026'),
  ('G11000R20AJ104', 'GIS', 'AJ-104', '10.00R20', 'Radial', 210.0, 15.0, 3250.0, 11.15, 3.43, 'Rib-Block', 'All Position', 'Long-haul paved-road transport; the only radial-only pattern', 'GIS ECO RETREAD Leaflet 2026'),
  ('G11100R20AJ104', 'GIS', 'AJ-104', '11.00R20', 'Radial', 210.0, 15.0, 3250.0, 11.15, 3.43, 'Rib-Block', 'All Position', 'Long-haul paved-road transport; the only radial-only pattern', 'GIS ECO RETREAD Leaflet 2026'),
  ('G111R225AJ104', 'GIS', 'AJ-104', '11R22.5', 'Radial', 220.0, 16.0, 3290.0, 12.0, 3.66, 'Rib-Block', 'All Position', 'Long-haul paved-road transport; the only radial-only pattern', 'GIS ECO RETREAD Leaflet 2026'),
  ('VG175016AJ101', 'GIS', 'AJ-101', '7.50-16', 'Bias', 145.0, 13.0, 2420.0, 4.8, 1.97, 'Lug', 'Drive', 'Unpaved roads and construction sites; standard spec for traction-oriented routes', 'GIS ECO RETREAD Leaflet 2026'),
  ('VG190020AJ101', 'GIS', 'AJ-101', '9.00-20', 'Bias', 193.0, 14.0, 3167.0, 10.1, 3.18, 'Lug', 'Drive', 'Unpaved roads and construction sites; standard spec for traction-oriented routes', 'GIS ECO RETREAD Leaflet 2026'),
  ('VG100020AJ101', 'GIS', 'AJ-101', '10.00-20', 'Bias', 204.0, 14.0, 3167.0, 10.1, 3.18, 'Lug', 'Drive', 'Unpaved roads and construction sites; standard spec for traction-oriented routes', 'GIS ECO RETREAD Leaflet 2026'),
  ('VG100020AJ301', 'GIS', 'AJ-301', '10.00-20', 'Bias', 205.0, 16.5, 3195.0, 10.1, 3.18, 'Block', 'Drive', 'Deepest skid depth in the range; mining and heavy-load routes, priced on wear life', 'GIS ECO RETREAD Leaflet 2026'),
  ('VG1100020AJ105', 'GIS', 'AJ-105', '10.00-20', 'Bias', 194.0, 15.0, 3200.0, 10.25, 3.35, 'Rib-Block', 'All Position', 'Mixed on/off-road routes; general-purpose replacement for bias vehicles', 'GIS ECO RETREAD Leaflet 2026'),
  ('VG110020AJ101', 'GIS', 'AJ-101', '11.00-20', 'Bias', 204.0, 14.0, 3245.0, 11.15, 3.44, 'Lug', 'Drive', 'Unpaved roads and construction sites; standard spec for traction-oriented routes', 'GIS ECO RETREAD Leaflet 2026'),
  ('VG1000R20AJ104', 'GIS', 'AJ-104', '10.00R20', 'Radial', 210.0, 15.0, 3250.0, 11.15, 3.43, 'Rib-Block', 'All Position', 'Long-haul paved-road transport; the only radial-only pattern', 'GIS ECO RETREAD Leaflet 2026'),
  ('VG1100R20AJ104', 'GIS', 'AJ-104', '11.00R20', 'Radial', 210.0, 15.0, 3250.0, 11.15, 3.43, 'Rib-Block', 'All Position', 'Long-haul paved-road transport; the only radial-only pattern', 'GIS ECO RETREAD Leaflet 2026'),
  ('VG111R225AJ104', 'GIS', 'AJ-104', '11R22.5', 'Radial', 220.0, 16.0, 3290.0, 12.0, 3.66, 'Rib-Block', 'All Position', 'Long-haul paved-road transport; the only radial-only pattern', 'GIS ECO RETREAD Leaflet 2026')
on conflict (sku) do update set
  brand = excluded.brand,
  pattern = excluded.pattern,
  size = excluded.size,
  construction = excluded.construction,
  base_width_mm = excluded.base_width_mm,
  skid_depth_mm = excluded.skid_depth_mm,
  roll_length_mm = excluded.roll_length_mm,
  weight_kg_roll = excluded.weight_kg_roll,
  weight_kg_m = excluded.weight_kg_m,
  tread_shape = excluded.tread_shape,
  position = excluded.position,
  application = excluded.application,
  source_catalog = excluded.source_catalog;
