-- products_spec_agr — AGR(농기계 바이어스) 제원표
-- 출처 ①: AGR_Tyre_Catalog.xlsx 'AGR Catalog' 시트 23규격 5패턴
--         (원본 = AGR-BIAS-Ascendo.pdf 2026-07, PT. Ascendo Internasional)
-- 출처 ②: 기존 public.specs_agr (ASCENDO AGR / ASCENDO AGR 2026 (Rungold) / DONGYING RUNGOLD BIAS 2026)
--         — 신규 카탈로그에 없는 제품의 하중·공기압·속도·용도를 이어받아 커버리지를 유지한다.
-- 단위: TD·OD·SW = mm, 하중능력 = kg, 공기압 = psi.
--
-- 구조: 제품 SKU 1행 기준(sku unique) — TBR·TBB·SOLID·PNEU 와 동일 규약.
-- 매칭 원칙:
--   1) PR 은 제품 SKU 의 정체성 — PR 이 다르면 매칭하지 않는다.
--   2) 신규 카탈로그(2026-07) 우선, 없으면 specs_agr(sku → 패턴·규격·PR → 패턴·규격 유일)에서 승계.
--   3) 패턴 별칭: 제품 'R4' = 카탈로그 'R4-B'. 신규 카탈로그에 순수 R4 행이 없고 Backhoe R4-B 계열이
--      10.5/80-18 · 12.5/80-18 · 19.5L-24 를 그대로 담고 있다. 12.5/80-18 은 두 출처가 2650kg/54psi 로
--      일치해 별칭이 검증되지만, 19.5L-24 는 값이 크게 달라 아래 '확인 필요'로 남긴다.
--
-- 결과: AGR 제품 68건 중 43건에 제원(신규 카탈로그 23 · specs_agr 승계 20). 미매칭 25건:
--   MAXAM 18건 전부(=specs_agr 에 MAXAM 행이 하나도 없음. 종전과 동일)
--   ASCENDO 7건 — ASC 500/70R24 R4 · 13.6-26 R2 12PR · 16.9-34 R1 12PR ·
--                 29x12.5-15 R1 8PR · 31x15.5-15 R1 8PR (두 출처 모두 해당 규격 없음)
--
-- 확인 필요 — 신규 카탈로그가 기존 specs_agr 값을 정정한 9건(하중 kg / 공기압 psi):
--   AGR-19524R412  19.5L-24 R4 12PR   3455@33 → 2145@30   ← 차이 큼. 기존 값은 Rungold 의 R4-A 계열,
--                                                            신규는 Ascendo 판매 카탈로그의 R4-B. 제조사 확인 권장
--   AGR-818R18     8-18   R1  8PR     1150@39 → 670@36
--   AGR-816R18     8-16   R1  8PR      650@30 → 870@54
--   AGR-20838R112  20.8-38 R1 12PR    3850@46 → 3575@33
--   AGR-16924R110  16.9-24 R1 12PR    2230@29 → 2440@33
--   AGR-13624R112  13.6-24 R1 12PR    2180@52 → 2035@42
--   AGR-13628R112  13.6-28 R1 12PR    1645@29 → 1910@36
--   AGR-95020R112  9.50-20 R1 12PR     940@38 → 1000@46
--   AGR-18434R112  18.4-34 R1 12PR    3375@33 → 3350@33
-- 카탈로그 원문 주석: R-2 (8-18) 하중 2,311 kg 은 동급 R-1 (8-18) 670 kg 대비 이례적으로 높아 제조사 확인 권장.
--   (AGR-818R28 'ASC 8-18 R2 8PR' 에 그대로 반영됨)
-- specs_agr 테이블은 삭제하지 않는다 — 제품에 연결되지 않은 Rungold 마스터 209행이 남아 있다.

create table if not exists public.products_spec_agr (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  brand text,
  pattern text,
  size text,
  ply_rating smallint,
  application text,                  -- 용도(Tractor·Paddy Field·Backhoe 등)
  tread_depth_mm numeric,
  overall_diameter_mm numeric,
  section_width_mm numeric,
  rim_size text,                     -- 림. 'W15L'·'5.50F' 등 문자 표기가 있어 텍스트
  max_load_kg numeric,
  max_pressure_psi numeric,
  tube_type text,                    -- TT(Tube Type) / TL(Tubeless)
  rated_speed_kmh numeric,           -- 신규 카탈로그에는 없음(specs_agr 승계분만)
  source_catalog text,
  created_at timestamptz not null default now()
);

alter table public.products_spec_agr enable row level security;
drop policy if exists agr_specs_read_auth on public.products_spec_agr;
create policy agr_specs_read_auth on public.products_spec_agr for select to authenticated using (true);
drop policy if exists agr_specs_write_admin on public.products_spec_agr;
create policy agr_specs_write_admin on public.products_spec_agr for all to authenticated
  using ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'))
  with check ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'));

insert into public.products_spec_agr
  (sku, brand, pattern, size, ply_rating, application, tread_depth_mm, overall_diameter_mm, section_width_mm, rim_size, max_load_kg, max_pressure_psi, tube_type, rated_speed_kmh, source_catalog)
values
  ('AGR-10165SKS110', 'ASCENDO', 'SKS-1', '10-16.5', 10, 'Backhoe', 17, 720, 265, '8.25', 2120, 75, 'TL', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-108018R412', 'ASCENDO', 'R4-B', '10.5/80-18', 12, 'Backhoe', 21, 869, 240, '9.00', 1935, 54, 'TL', null, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-11224R112', 'ASCENDO', 'R-1', '11.2-24', 12, 'Tractor', 26, 1110, 300, 'W10', 1500, 52, 'TT', null, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-11228R112', 'ASCENDO', 'R-1', '11.2-28', 12, 'Tractor', 32, 1190, 300, 'W11', 1800, 46, 'TT', null, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-12165SKS112', 'ASCENDO', 'SKS-1', '12-16.5', 12, 'Backhoe', 19, 760, 290, '9.75', 2800, 80, 'TL', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-12424R112', 'ASCENDO', 'R-1', '12.4-24', 12, 'Tractor', 28, 1130, 315, 'W11', 1750, 48, 'TT', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-12424R1W12', 'ASCENDO', 'R-1W', '12.4-24', 12, 'Paddy Field', 39, 1105, 315, 'W11', 1600, 48, 'TT', 40, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-12424R212', 'ASCENDO', 'R2', '12.4-24', 12, '트랙터 (Traktor)', null, null, null, null, 1750, 48, null, 30, 'ASCENDO AGR'),
  ('AGR-1258018R412', 'ASCENDO', 'R4-B', '12.5/80-18', 12, 'Backhoe', 22, 963, 300, '9.00', 2650, 54, 'TL', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-13624R112', 'ASCENDO', 'R-1', '13.6-24', 12, 'Tractor', 20.5, 1165, 315, 'W12', 2035, 42, 'TT', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-13628R112', 'ASCENDO', 'R-1', '13.6-28', 12, 'Tractor', 26, 1260, 340, 'W12', 1910, 36, 'TT', null, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-14924R112', 'ASCENDO', 'R-1', '14.9-24', 12, 'Tractor', 27, 1187, 378, 'W13', 2120, 35, 'TT', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-14924R1W12', 'ASCENDO', 'R1W', '14.9-24', 12, 'Agriculture Tyres', null, null, null, null, 2000, 38, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-14928R1W12', 'ASCENDO', 'R1W', '14.9-28', 12, 'Agriculture Tyres', null, null, null, null, 2120, 36, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-15538R1W12', 'ASCENDO', 'R1W', '15.5-38', 12, 'Agriculture Tyres', null, null, null, null, 2350, 35, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-16924R110', 'ASCENDO', 'R-1', '16.9-24', 12, 'Tractor', 35, 1255, 415, 'W15L', 2440, 33, 'TT', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-16924R1W12', 'ASCENDO', 'R1W', '16.9-24', 12, 'Agriculture Tyres', null, null, null, null, 2300, 33, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-16928R110', 'ASCENDO', 'R-1', '16.9-28', 12, 'Tractor', 34, 1360, 430, 'W15L', 2380, 29, 'TT', null, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-16928R1W12', 'ASCENDO', 'R1W', '16.9-28', 12, 'Agriculture Tyres', null, null, null, null, 3875, 44, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-16928R412', 'ASCENDO', 'R4', '16.9-28', 12, 'Industrial Tractor Tyres', null, null, null, null, 3450, 38, null, 30, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-16930R112', 'ASCENDO', 'R-1', '16.9-30', 12, 'Tractor', 38, 1430, 410, 'W15L', 2725, 35, 'TT', null, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-16930R1W12', 'ASCENDO', 'R1W', '16.9-30', 12, 'Agriculture Tyres', null, null, null, null, 2500, 33, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-16934R1W12', 'ASCENDO', 'R1W', '16.9-34', 12, 'Agriculture Tyres', null, null, null, null, 2720, 33, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-18426R1W12', 'ASCENDO', 'R1W', '18.4-26', 12, 'Agriculture Tyres', null, null, null, null, 2650, 32, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-18430R112', 'ASCENDO', 'R-1', '18.4-30', 12, 'Tractor', 33, 1520, 467, 'W16L', 3150, 33, 'TT', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-18430R1W12', 'ASCENDO', 'R1W', '18.4-30', 12, 'Agriculture Tyres', null, null, null, null, 2900, 32, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-18434R112', 'ASCENDO', 'R-1', '18.4-34', 12, 'Tractor', 33, 1655, 467, 'W16L', 3350, 33, 'TT', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-18434R1W12', 'ASCENDO', 'R1W', '18.4-34', 12, 'Agriculture Tyres', null, null, null, null, 3000, 32, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-18438R1W12', 'ASCENDO', 'R1W', '18.4-38', 12, 'Agriculture Tyres', null, null, null, null, 3250, 32, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-18446R1W16', 'ASCENDO', 'R1W', '18.4-46', 16, 'Agriculture Tyres', null, null, null, null, 4475, 46, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-19524R412', 'ASCENDO', 'R4-B', '19.5L-24', 12, 'Backhoe', 22, 1235, 485, 'W16L', 2145, 30, 'TL', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-20838R112', 'ASCENDO', 'R-1', '20.8-38', 12, 'Farm (SH111)', 36, 1720, 450, 'W16L', 3575, 33, 'TT', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-20838R1W12', 'ASCENDO', 'R1W', '20.8-38', 12, 'Agriculture Tyres', null, null, null, null, 3875, 32, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-20838R1W14', 'ASCENDO', 'R1W', '20.8-38', 14, 'Agriculture Tyres', null, null, null, null, 3875, 32, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-24532R1W16', 'ASCENDO', 'R1W', '24.5-32', 16, 'Agriculture Tyres', null, null, null, null, 4500, 30, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-305L32R1W18', 'ASCENDO', 'R1W', '30.5L-32', 18, 'Agriculture Tyres', null, null, null, null, 5250, 28, null, 40, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-40060155I314', 'ASCENDO', 'I3', '400/60-15.5', 14, 'Farm Implement Tyres', null, null, null, null, 2800, 22, null, 30, 'ASCENDO AGR 2026 (Rungold)'),
  ('AGR-816R18', 'ASCENDO', 'R-1', '8-16', 8, 'Tractor', 20, 790, 205, '5.50F', 870, 54, 'TT', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-818R18', 'ASCENDO', 'R-1', '8-18', 8, 'Tractor', 20, 830, 205, '6.00', 670, 36, 'TT', 30, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-818R28', 'ASCENDO', 'R-2', '8-18', 8, 'Paddy Field', 45, 840, 220, '5.50', 2311, 42, 'TT', null, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-95020R112', 'ASCENDO', 'R-1', '9.50-20', 12, 'Tractor', 25, 995, 220, 'W8', 1000, 46, 'TT', null, 'ASCENDO AGR-BIAS 2026-07'),
  ('AGR-95024R112', 'ASCENDO', 'R-1', '9.50-24', 12, 'Tractor', 26, 1035, 240, 'W8', 1110, 41, 'TT', null, 'ASCENDO AGR-BIAS 2026-07'),
  ('OTR1-23126R3', 'ASCENDO', 'R3', '23.1-26', 12, 'Road Rollers Tyres', null, null, null, null, 3610, 25, null, 30, 'ASCENDO AGR 2026 (Rungold)')
on conflict (sku) do update set
  brand = excluded.brand,
  pattern = excluded.pattern,
  size = excluded.size,
  ply_rating = excluded.ply_rating,
  application = excluded.application,
  tread_depth_mm = excluded.tread_depth_mm,
  overall_diameter_mm = excluded.overall_diameter_mm,
  section_width_mm = excluded.section_width_mm,
  rim_size = excluded.rim_size,
  max_load_kg = excluded.max_load_kg,
  max_pressure_psi = excluded.max_pressure_psi,
  tube_type = excluded.tube_type,
  rated_speed_kmh = excluded.rated_speed_kmh,
  source_catalog = excluded.source_catalog;
