-- products_spec_tbb — TBB(바이어스 트럭·버스) 제원표
-- 출처: TBB_브랜드별_타이어카탈로그_규격정리_20260803.xlsx '통합' 시트 69행
--       (원본 PDF: JK Tyre.pdf / TBB TIRON.pdf / TBB Ascendo.pdf — Google Drive '3. CATALOG')
--       브랜드 구성: JK Tyre 13건(OTR 3 포함) / TIRON 47건(지게차 5 포함) / Ascendo 9건
-- 단위: OD·SW·트레드깊이 mm, 하중 kg, 공기압 psi, 중량 kg. 빈 칸 = 원본 카탈로그에 수치 없음.
--
-- 구조: 제품 SKU 1행 기준(sku unique). 스펙 탭은 products 를 행으로 나열하고 sku 로 제원을 채우므로,
--       카탈로그 행을 제품 설명(description)과 오프라인 매칭해 SKU 단위로 펼쳐 넣는다.
-- 매칭 원칙(TBR 갱신과 동일):
--   1) PR 은 제품 SKU 의 정체성 — 카탈로그 PR 과 다르면 매칭하지 않는다.
--   2) brand·패턴·규격·PR 일치가 기본. 후보가 여럿이면 구조·사양(LM/SHD/PRIME/V-LUG/RE/ML/Ultra Grip)으로 가른다.
--   3) 설명에 PR 이 없으면(예: 'ASC 10.00-20 AB635') 해당 패턴·규격 카탈로그 행이 유일할 때만 채운다.
--   * JK Tyre 는 PR 열이 비어 있고 구조·사양이 'G/14'·'H/16' 형태라 여기서 PR 을 읽었다.
--   * 패턴 별칭: 제품 'HS431' = 카탈로그 '431'.
--
-- 결과: 제품 69건 중 58건 매칭, 11건 미매칭(아래).
--   [PR 불일치 — 제원 미기입]
--     10120070200121001  TR 7.00-16 HS307 12       DB 12PR ↔ 카탈로그 14PR
--     110020JETRPLUS18   JK 11.00-20 JET R PLUS 18PR  DB 18PR ↔ 카탈로그 16PR
--   [카탈로그에 해당 패턴·규격 없음]
--     10110120040181001  TR 12.00-20 HS700 PRIME 18PR (카탈로그 HS700 은 11.00-20 만)
--     110020JETXTRALOAD16 JK 11.00-20 JET XTRA LOAD 16PR (카탈로그는 8.25-16 만, 11.00-20 은 DX 만)
--     B1-130024AB635 / B1-75016AB635 / B1-82516AB635 / B1-75016AB616 / B1-82516AB616
--     B1-75016AB651 / B1-82516AB651  (Ascendo TBB 카탈로그 9행에 없는 규격)
-- 카탈로그에만 있고 TBB 제품에 없는 행 11건:
--   JK Tyre VEM AS 14.00-24 28PR · VEM 99 18.00-25 40PR (OTR 품목)
--   TIRON HS307 7.00-16 14PR · 431 11.00-20 18PR · HS700 11.00-20 18PR PRIME · HS320 10.00-20 16PR PRIME
--   TIRON HS800 지게차(공기압) 6.00-9 / 6.50-10 / 7.00-12 / 8.25-15 / 28X9-15 (PNEUMATIC 품목)
-- 주의: weight_kg 는 카탈로그 값(Ascendo 9건만 존재)이며 products_priced.weight_kg 와 9건 모두 다르다
--       (예: AB635 10.00-20 카탈로그 54 ↔ 제품 49). 스펙 탭은 카탈로그 값을 표시한다 — 확인 필요.
--       JK Tyre OTR(VEM AS·VEM 99) 하중은 Transport 50 kmph 기준(Loading 10 kmph 기준은 비고 열).

create table if not exists public.products_spec_tbb (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  brand text,
  pattern text,
  size text,
  ply_rating smallint,
  tire_type text,                    -- 유형: TBB (Rib) / (Lug) / (Rib-Lug) / (All Position) 등
  construction text,                 -- 구조·사양: LM·SHD·PRIME·ML·RE·V-LUG·Ultra Grip / JK 는 G/14·H/16
  rim_size text,                     -- 표준 림(inch). '6.00G'·'8.50/1.8' 등 문자 표기가 있어 텍스트
  overall_diameter_mm numeric,
  section_width_mm numeric,
  tread_depth_mm numeric,
  load_index text,
  weight_kg numeric,
  single_load_kg numeric,
  single_pressure_psi numeric,
  dual_load_kg numeric,
  dual_pressure_psi numeric,
  application text,                  -- 용도
  remarks text,                      -- 비고
  source_catalog text,
  created_at timestamptz not null default now()
);

alter table public.products_spec_tbb enable row level security;
drop policy if exists tbb_specs_read_auth on public.products_spec_tbb;
create policy tbb_specs_read_auth on public.products_spec_tbb for select to authenticated using (true);
drop policy if exists tbb_specs_write_admin on public.products_spec_tbb;
create policy tbb_specs_write_admin on public.products_spec_tbb for all to authenticated
  using ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'))
  with check ((((auth.jwt() -> 'app_metadata') ->> 'role') = 'super_admin'));

insert into public.products_spec_tbb
  (sku, brand, pattern, size, ply_rating, tire_type, construction, rim_size, overall_diameter_mm, section_width_mm, tread_depth_mm, load_index, weight_kg, single_load_kg, single_pressure_psi, dual_load_kg, dual_pressure_psi, application, remarks, source_catalog)
values
  ('100020JETACESNI16', 'JK TYRE', 'JET ACE', '10.00-20', 16, 'TBB (Rib)', 'H/16', '7.50', 1082, 280, 18, '146/144 K', null, 3000, 115, 2800, 105, 'All Position (전륜/조향축)', 'App. Flaps 20N', 'JK Tyre TBB 2026-08-03'),
  ('100020JETPOWER10016', 'JK TYRE', 'JET POWER 100', '10.00-20', 16, 'TBB (Lug)', 'H/16', '7.50', 1058, 272, 22, '146/144 G', null, 3000, 115, 2800, 105, 'Drive (구동축)', 'App. Flaps 20N', 'JK Tyre TBB 2026-08-03'),
  ('100020JETXTRALOADDX1', 'JK TYRE', 'JET XTRA LOAD DX', '10.00-20', 16, 'TBB (Lug)', 'H/16', '7.50', 1062, 280, 22, '146/144 K', null, 3000, 115, 2800, 105, 'Drive / Heavy Duty (구동·중하중)', 'App. Flaps 20N', 'JK Tyre TBB 2026-08-03'),
  ('10110090095161001', 'TIRON', 'HF5', '9.00-20', 16, 'TBB (Rib)', null, '7.00', 1022, 262, 12.5, null, null, 2720, 120, 2390, 110, 'Bus / Truck (버스·트럭)', null, 'TIRON TBB 2026-08-03'),
  ('10110090110161001', 'TIRON', 'HT5', '9.00-20', 16, 'TBB (Lug)', null, '7.00', 1024, 262, 17.5, null, null, 2720, 120, 2390, 110, 'Truck (트럭)', null, 'TIRON TBB 2026-08-03'),
  ('10110100030161001', 'TIRON', '431', '10.00-20', 16, 'TBB (Lug)', 'ML', '7.50', 1080, 285, 29, null, null, 3000, 115, null, null, 'Mining & Logging (광산·벌목)', 'ML = Mining & Logging / 복륜 사용 불가', 'TIRON TBB 2026-08-03'),
  ('10110100206161004', 'TIRON', 'HS309', '10.00-20', 16, 'TBB (Rib-Lug)', 'LM', '7.50', 1080, 285, 20.5, null, null, 3000, 115, 2800, 105, 'Dump / Mixer / Trailer (덤프·믹서·트레일러)', 'LM = Long Mileage', 'TIRON TBB 2026-08-03'),
  ('10110100212161002', 'TIRON', 'HS311', '10.00-20', 16, 'TBB (Rib)', 'SHD', '7.50', 1076, 285, 17.5, null, null, 3000, 115, 2800, 105, 'Mixer / Dump (믹서·덤프)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10110100226161002', 'TIRON', 'HS314', '10.00-20', 16, 'TBB (Lug)', 'SHD', '7.50', 1080, 285, 22, null, null, 3000, 115, 2800, 105, 'Dump (덤프)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10110100227161001', 'TIRON', 'HS315', '10.00-20', 16, 'TBB (Rib)', 'LM', '7.50', 1076, 285, 16.5, null, null, 3000, 115, 2800, 105, 'Mixer / Dump / Trailer (믹서·덤프·트레일러)', 'LM = Long Mileage', 'TIRON TBB 2026-08-03'),
  ('10110100231181001', 'TIRON', 'HS320', '10.00-20', 16, 'TBB (Rib-Lug)', 'SHD', '7.50', 1080, 285, 20.5, null, null, 3000, 115, 2800, 105, 'Dump / Mixer / Trailer (덤프·믹서·트레일러)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10110100500161002', 'TIRON', 'HS500', '10.00-20', 16, 'TBB (Rib)', 'LM', '7.50', 1076, 285, 16.5, null, null, 3000, 115, 2800, 105, 'Mixer / Dump / Trailer (믹서·덤프·트레일러)', 'LM = Long Mileage', 'TIRON TBB 2026-08-03'),
  ('10110100500161003', 'TIRON', 'HS500', '10.00-20', 16, 'TBB (Rib)', 'SHD', '7.50', 1076, 285, 16.5, null, null, 3000, 115, 2800, 105, 'Mixer / Dump / Trailer (믹서·덤프·트레일러)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10110110212161003', 'TIRON', 'HS311', '11.00-20', 16, 'TBB (Rib)', 'SHD', '8.00', 1095, 295, 18.5, null, null, 3350, 115, 2900, 105, 'Trailer / Dump (트레일러·덤프)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10110110222361001', 'TIRON', 'HS320', '11.00-20', 16, 'TBB (Rib-Lug)', 'PRIME', '8.00', 1095, 295, 21.5, null, null, 3350, 115, 2900, 105, 'Dump / Trailer (덤프·트레일러)', 'PRIME = Premium Model', 'TIRON TBB 2026-08-03'),
  ('10110110222361002', 'TIRON', 'HS320', '11.00-20', 16, 'TBB (Rib-Lug)', 'SHD', '8.00', 1095, 295, 21.5, null, null, 3350, 115, 2900, 105, 'Dump / Trailer (덤프·트레일러)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10110110224161003', 'TIRON', 'HS314', '11.00-20', 16, 'TBB (Lug)', 'SHD', '8.00', 1100, 295, 23.5, null, null, 3350, 115, 2900, 105, 'Dump / Trailer (덤프·트레일러)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10110110224161006', 'TIRON', 'HS314', '11.00-20', 16, 'TBB (Lug)', 'LM', '8.00', 1100, 295, 23.5, null, null, 3350, 115, 2900, 105, 'Dump / Trailer (덤프·트레일러)', 'LM = Long Mileage', 'TIRON TBB 2026-08-03'),
  ('10110110500161002', 'TIRON', 'HS500', '11.00-20', 16, 'TBB (Rib)', 'LM', '8.00', 1090, 290, 17.5, null, null, 3350, 115, 2900, 105, 'Dump / Trailer (덤프·트레일러)', 'LM = Long Mileage', 'TIRON TBB 2026-08-03'),
  ('10110110500161003', 'TIRON', 'HS500', '11.00-20', 16, 'TBB (Rib)', 'SHD', '8.00', 1090, 290, 17.5, null, null, 3350, 115, 2900, 105, 'Dump / Trailer (덤프·트레일러)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10110110700161004', 'TIRON', 'HS700', '11.00-20', 18, 'TBB (Lug)', 'V-LUG', '8.00', 1105, 295, 23, null, null, 3550, 125, 3075, 115, 'Dump / Trailer (덤프·트레일러)', null, 'TIRON TBB 2026-08-03'),
  ('10110120020181001', 'TIRON', 'HS366', '12.00-20', 18, 'TBB (Rib)', null, '8.50', 1132, 325, 16.5, null, null, 3750, 115, 3550, 105, 'Heavy Truck / Dump (대형트럭·덤프)', null, 'TIRON TBB 2026-08-03'),
  ('10110120210181001', 'TIRON', 'HS389', '12.00-20', 18, 'TBB (Lug)', null, '8.50', 1130, 320, 21, null, null, 3724, 115, 3266, 105, 'Heavy Dump (대형덤프)', null, 'TIRON TBB 2026-08-03'),
  ('10120070110141001', 'TIRON', 'HT5', '7.00-16', 14, 'TBB (Lug)', null, '5.50', 779, 199, 12.5, null, null, 1400, 105, 1335, 105, 'Light Truck (소형트럭)', null, 'TIRON TBB 2026-08-03'),
  ('10120070204101003', 'TIRON', 'HS317', '7.00-16', 14, 'TBB (Rib)', null, '5.50', 782, 199, 10.8, null, null, 1400, 105, 1335, 105, 'Light Truck (소형트럭)', null, 'TIRON TBB 2026-08-03'),
  ('10120075031141001', 'TIRON', 'HS600', '7.50-16', 14, 'TBB (Lug)', 'Ultra Grip', '6.00', 824, 215, 17.5, null, null, 1510, 94, 1440, 94, 'Light Truck (소형트럭)', null, 'TIRON TBB 2026-08-03'),
  ('10120075090141003', 'TIRON', 'HF1', '7.50-16', 14, 'TBB (Rib)', 'RE', '6.00', 808, 215, 10.8, null, null, 1510, 94, 1440, 94, 'Light Truck (소형트럭)', null, 'TIRON TBB 2026-08-03'),
  ('10120075200141002', 'TIRON', 'HS307', '7.50-16', 14, 'TBB (Lug)', 'SHD', '6.00', 812, 215, 17.5, null, null, 1510, 94, 1440, 94, 'Light Truck / Dump (소형트럭·덤프)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10120075200141004', 'TIRON', 'HS307', '7.50-16', 14, 'TBB (Lug)', 'LM', '6.00', 812, 215, 17.5, null, null, 1510, 94, 1440, 94, 'Light Truck / Dump (소형트럭·덤프)', 'LM = Long Mileage', 'TIRON TBB 2026-08-03'),
  ('10120075203141001', 'TIRON', 'HS308', '7.50-16', 14, 'TBB (Rib)', 'LM', '6.00', 817, 215, 12, null, null, 1510, 94, 1440, 94, 'Light Truck (소형트럭)', 'LM = Long Mileage', 'TIRON TBB 2026-08-03'),
  ('10120075203161001', 'TIRON', 'HS308', '7.50-16', 14, 'TBB (Rib)', 'SHD', '6.00', 817, 215, 12, null, null, 1510, 94, 1440, 94, 'Light Truck (소형트럭)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10120075206141002', 'TIRON', 'HS309', '7.50-16', 14, 'TBB (Rib-Lug)', 'LM', '6.00', 820, 215, 17.5, null, null, 1510, 94, 1440, 94, 'Light Truck (소형트럭)', 'LM = Long Mileage', 'TIRON TBB 2026-08-03'),
  ('10120075206141003', 'TIRON', 'HS309', '7.50-16', 14, 'TBB (Rib-Lug)', 'SHD', '6.00', 820, 215, 17.5, null, null, 1510, 94, 1440, 94, 'Light Truck (소형트럭)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10120075222141001', 'TIRON', 'HS314', '7.50-16', 14, 'TBB (Lug)', 'SHD', '6.00', 820, 215, 17.5, null, null, 1510, 94, 1440, 94, 'Light Truck / Dump (소형트럭·덤프)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10120075233121001', 'TIRON', 'HS317', '7.50-15', 12, 'TBB (Rib)', null, '6.00', 788, 215, 12, null, null, 1400, 87, 1320, 87, 'Light Truck (소형트럭)', null, 'TIRON TBB 2026-08-03'),
  ('10120075233141002', 'TIRON', 'HS317', '7.50-16', 14, 'TBB (Rib)', 'SHD', '6.00', 817, 215, 12, null, null, 1510, 94, 1440, 94, 'Light Truck (소형트럭)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10120075233141004', 'TIRON', 'HS317', '7.50-16', 14, 'TBB (Rib)', 'LM', '6.00', 817, 215, 12, null, null, 1510, 94, 1440, 94, 'Light Truck (소형트럭)', 'LM = Long Mileage', 'TIRON TBB 2026-08-03'),
  ('10120075233141005', 'TIRON', 'HS320', '7.50-16', 14, 'TBB (Rib-Lug)', 'SHD', '6.00', 835, 215, 17.5, null, null, 1510, 94, 1440, 94, 'Light Truck (소형트럭)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10120080090141004', 'TIRON', 'HF1', '8.25-16', 14, 'TBB (Rib)', 'SHD', '6.50', 855, 230, 11.8, null, null, 1710, 83, 1630, 83, 'Light / Medium Truck (소·중형트럭)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10120080190141001', 'TIRON', 'HS320', '8.25-16', 14, 'TBB (Rib-Lug)', 'SHD', '6.50', 860, 225, 17, null, null, 1750, 83, 1650, 83, 'Light / Medium Truck (소·중형트럭)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('10120085222141001', 'TIRON', 'HS314', '8.25-16', 14, 'TBB (Lug)', 'SHD', '6.50', 860, 228, 19, null, null, 1710, 83, 1630, 83, 'Light / Medium Truck (소·중형트럭)', 'SHD = Super Heavy Duty', 'TIRON TBB 2026-08-03'),
  ('110020JETRPLUS16', 'JK TYRE', 'JET R PLUS', '11.00-20', 16, 'TBB (Rib)', 'H/16', '8.00', 1095, 291, 17, '150/145 J', null, 3250, 115, 2900, 105, 'All Position (전륜/조향축)', 'App. Flaps 20RR', 'JK Tyre TBB 2026-08-03'),
  ('110020JETXTRALOADDX1', 'JK TYRE', 'JET XTRA LOAD DX', '11.00-20', 16, 'TBB (Lug)', 'H/16', '8.00', 1085, 280, 23, '150/145 G', null, 3350, 115, 2900, 105, 'Drive / Heavy Duty (구동·중하중)', 'App. Flaps 20RR', 'JK Tyre TBB 2026-08-03'),
  ('120020JETROCKXD18', 'JK TYRE', 'JET ROCK XD', '12.00-20', 18, 'OTR (Bias, TT)', 'TT', '8.50', 1141, 300, 29, 'ML 2', null, 3350, 105, null, null, 'Underground Mining (지하광산)', '대체 림 8.0 / 9.0', 'JK Tyre TBB 2026-08-03'),
  ('120020TIPPERKING20', 'JK TYRE', 'TIPPER KING', '12.00-20', 20, 'TBB (Lug, TT)', 'TT', '8.50/1.8', 1125, 312, null, '150 F', null, 3450, 115, null, null, 'Tipper / Dump (덤프트럭)', '정하중반경(SLR) 543 mm', 'JK Tyre TBB 2026-08-03'),
  ('75016JETRIBXTRA14', 'JK TYRE', 'JET RIB XTRA', '7.50-16', 14, 'TBB (Rib)', 'G/14', '6.00', 813, 216, 12, '122/121 G', null, 1510, 95, 1440, 95, 'All Position (전륜/조향축)', 'App. Flaps 16N', 'JK Tyre TBB 2026-08-03'),
  ('75016JETTRAK3914', 'JK TYRE', 'JET-TRAK 39', '7.50-16', 14, 'TBB (Lug)', 'G/14', '6.00', 831, 225, 18, '122/121 J', null, 1510, 95, 1440, 95, 'Drive (구동축)', 'App. Flaps 16N', 'JK Tyre TBB 2026-08-03'),
  ('75016TRAKTUFXTRA14', 'JK TYRE', 'TRAK TUF XTRA', '7.50-16', 14, 'TBB (Lug)', 'G/14', '6.00', 823, 215, 17, '122/121 J', null, 1510, 95, 1440, 95, 'Drive / Trailer (구동·트레일러)', 'App. Flaps 16N', 'JK Tyre TBB 2026-08-03'),
  ('82516JETXTRALOAD14', 'JK TYRE', 'JET XTRA LOAD', '8.25-16', 14, 'TBB (Lug)', 'G/14', '6.50', 850, 280, 18, '126/125 J', null, 1710, 83, 1630, 83, 'Drive / Heavy Duty (구동·중하중)', 'App. Flaps 20N', 'JK Tyre TBB 2026-08-03'),
  ('B1-100020AB111', 'ASCENDO', 'AB111', '10.00-20', 18, 'TBB (All Position)', null, '7.50', 1038, 198, 18, '150/145 G', 59.5, 3350, 120, 2900, 120, 'All Position (전 축 위치)', null, 'Ascendo TBB 2026-08-03'),
  ('B1-100020AB313', 'ASCENDO', 'AB313', '10.00-20', 18, 'TBB (All Position)', null, '7.50', 1055, 215, 21, '150/145 G', 62.5, 3350, 120, 2900, 120, 'All Position (전 축 위치)', null, 'Ascendo TBB 2026-08-03'),
  ('B1-100020AB316', 'ASCENDO', 'AB316', '10.00-20', 18, 'TBB (All Position)', null, '7.50', 1055, 198, 20.5, '150/145 G', 57, 3350, 125, 2900, 125, 'All Position (전 축 위치)', null, 'Ascendo TBB 2026-08-03'),
  ('B1-100020AB635', 'ASCENDO', 'AB635', '10.00-20', 16, 'TBB (All Position)', null, '7.50', 1054, 275, 14.5, '146/144 K', 54, 3000, 110, 2800, 110, 'All Position (전 축 위치)', '내마모·내펑크 성능 / 일반 포장도로용', 'Ascendo TBB 2026-08-03'),
  ('B1-110020AB112', 'ASCENDO', 'AB112', '11.00-20', 18, 'TBB (All Position)', null, '8.00', 1044, 200, 19, '153/148 G', 55, 3650, 125, 3150, 125, 'All Position (전 축 위치)', null, 'Ascendo TBB 2026-08-03'),
  ('B1-110020AB535', 'ASCENDO', 'AB535', '11.00-20', 18, 'TBB (All Position)', null, '8.00', 1080, 221, 23.5, '153/148 G', 58, 3650, 125, 3150, 125, 'All Position (전 축 위치)', null, 'Ascendo TBB 2026-08-03'),
  ('B1-110020AB635', 'ASCENDO', 'AB635', '11.00-20', 16, 'TBB (All Position)', null, '8.00', 1072, 260, 14.5, '150/145 K', 54, 3350, 110, 2900, 110, 'All Position (전 축 위치)', '내마모·내펑크 성능 / 일반 포장도로용', 'Ascendo TBB 2026-08-03'),
  ('B1-75016AB111', 'ASCENDO', 'AB111', '7.50-16', 14, 'TBB (All Position)', null, '6.00G', 799, 157, 14, '122/118 J', 24.5, 1500, 105, 1320, 105, 'All Position (전 축 위치)', null, 'Ascendo TBB 2026-08-03'),
  ('B1-75016AB313', 'ASCENDO', 'AB313', '7.50-16', 14, 'TBB (All Position)', null, '6.00G', 815, 170, 18.5, '122/118 J', 25.5, 1500, 105, 1320, 105, 'All Position (전 축 위치)', null, 'Ascendo TBB 2026-08-03')
on conflict (sku) do update set
  brand = excluded.brand,
  pattern = excluded.pattern,
  size = excluded.size,
  ply_rating = excluded.ply_rating,
  tire_type = excluded.tire_type,
  construction = excluded.construction,
  rim_size = excluded.rim_size,
  overall_diameter_mm = excluded.overall_diameter_mm,
  section_width_mm = excluded.section_width_mm,
  tread_depth_mm = excluded.tread_depth_mm,
  load_index = excluded.load_index,
  weight_kg = excluded.weight_kg,
  single_load_kg = excluded.single_load_kg,
  single_pressure_psi = excluded.single_pressure_psi,
  dual_load_kg = excluded.dual_load_kg,
  dual_pressure_psi = excluded.dual_pressure_psi,
  application = excluded.application,
  remarks = excluded.remarks,
  source_catalog = excluded.source_catalog;
